package com.tal.coupons.exceptions;

import com.tal.coupons.enums.ErrorType;

/**
 *	This class provides a custom exception mechanism which is used throughout the program in order to identify various errors
 *	via error id's.
 * @author Sol Invictus
 *
 */
public class ApplicationException extends Exception {
	
	
	/* Apparantly we need to define serialVersionID because class 'Exception' inherits from class 'Throwable' which implements 
	 * the 'Serializable' interface. Here, I used the default value of 1L generated by the IDE.
	*/
	private static final long serialVersionUID = 1L;
	
	private ErrorType errorType;

	
	public ApplicationException(ErrorType errorType, Throwable cause, String message) {
		super(message, cause);
		this.setErrorType(errorType);
	}
	
	public ErrorType getErrorType() {
		return errorType;
	}

	public void setErrorType(ErrorType errorType) {
		this.errorType = errorType;
	}

	
	
}
